### ISSUE TITLE
Answer for #2

### ISSUE THREAD

**Issue by alvacat** [learn-co-curriculum/dsc-measures-of-dispersion-quiz#2]
I think the answer for number 2 is incorrect. Or the question has a typo.

The problem says the dataset is ordered so, even though it's formatted weird, it seems that the dataset is: 44  49  50  51  53  57  58  62  66  66  68  71  75  77  80  85 which would give a median value of 64, a Q1 value of 52, and a Q3 of 73.  That would make the IQR equal to21.

Alternately, the dataset is unordered and the question has a typo. (If it's unordered, the median is 5.5, Q1 is 4 and Q3 is 7 which gives an IQR of 3.)

**Comment by LoreDirick** [comment]
Hi @alvacat - we removed this question because it was confusing. Thanks for flagging!
